pipeline:
  - plugins.list_modules
  - plugins.create_manifest
  - broadcast: 'gm4_*'
    extend: 'beet.yaml'
    pipeline:
      - plugins.output_release

meta:
  gm4_manifest:
    save_directory: release
  autosave:
    link: false
