extend: '../common.yaml'

id: gm4_disassemblers
name: Disassemblers
version: '1.0.0'
description: Break apart gold and iron tools and weapons for materials. Attach this to a mobfarm to finally make use of those extra armour sets!

data_pack:
  load: .

pipeline:
  - gm4_disassemblers.generate_loot
  - smithed_libraries.actionbar
  - data_pack:
      load: '../lib_forceload'
