name: Check and build modules

on:
  push:
    branches: [ master, ver/1.18, ver/1.17, ver/1.16, ver/1.15, ver/1.14, ver/1.13 ]
  pull_request:
  workflow_dispatch:

env:
  VERSION: '1.19'
  PATCH_PREFIX: 19000
  COMMIT_MSG: ${{ github.event.head_commit.message }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: mcbeet/check-commands@v1
        with:
          minecraft: ${{ env.VERSION }}
          source: base gm4_* lib_*
          version: '0.52.2'

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Checkout release branch
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v2
        with:
          ref: release
          path: release

      - name: Fetch pull request base
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.base_ref }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1.2.1
        with:
          virtualenvs-in-project: true

      - name: Setup cache
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install

      - name: Build all modules
        if: github.event_name != 'pull_request'
        run: poetry run beet build -p beet-release.yaml

      - name: Build modules from pull request
        if: github.event_name == 'pull_request'
        run: poetry run beet --set 'meta.pull_request_base=origin/${{ github.base_ref }}' build -p beet-release.yaml

      - name: Upload artifact
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: 'Modules for pull request #${{ github.event.number }}'
          path: ${{ github.workspace }}/out/

      - name: Commit release
        if: github.event_name != 'pull_request'
        run: |
          git config --global user.email "${{ github.event.head_commit.author.email }}"
          git config --global user.name "${{ github.event.head_commit.author.username }}"
          mkdir -p release/$VERSION
          mv -f out/* release/$VERSION
          cd release
          git add .
          git commit -m "🚀 ${{ github.event.after }} $COMMIT_MSG"

      - name: Push release
        if: github.event_name != 'pull_request'
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: release
          branch: release
